# AntiSilverFish Configuration
# Set to true or false depending on your preference and then reload with /antisilverfish reload
# Default permission: antisilverfish.admin

# Completely disables any Infestation Potion Effects for everyone
Disable_Infestation_Potions: true
# Prevents Silverfish from spawning when breaking Infested Blocks
Disable_Silverfish_Spawning: true
# Prevents Silverfish from re-entering Blocks
Disable_Silverfish_Reentering: true
