# AntiSilverFish Configuration
# Set to tue of false depending on your preference and then reload with /antisilverfish reload
# Default permission: antisilverfish.admin

# Completely disables any Infestation Potion Effects for everyone
Disable_infestation_potions: true
# Prevents Silverfish from spawning when breaking an Infested Blocks
Disable_silverfish_spawning: true
# Prevent Silverfish from re-entering Blocks
Disable_silverfish_reentering: true