name: ${name}
version: ${version}
main: me.duart.bukkitAntiSilverFish.AntiSilverFish
api-version: ${apiVersion}
authors: [ DaveDuart ]
description: ${description}

commands:
  antisilverfish:
    description: Plugin's main command